### ISSUE TITLE
Support more benchmark functions

### ISSUE THREAD

**Issue by HaaLeo** [HaaLeo/swarmlib#15]
# Description
The currently used benchmark functions namely [ackley](https://www.sfu.ca/~ssurjano/ackley.html) and [michalewicz](https://www.sfu.ca/~ssurjano/michal.html) are hard coded in the library.
Consuming the functions instead via an external library (pypi package) could enable access to way more functions.

**Comment by NimishVerma** [comment]
I would like to suggest `pygmo` for this. It even has benchmark CEC functions :). It is implementable but due to the project structure, there is a repetition of code. Each algorithm has its own subparser to get the argument of the evaluation function, is it possible to add this in the main parser file?

**Comment by HaaLeo** [comment]
I took a look at [`pygmo`](https://esa.github.io/pygmo2/index.html). Since swarmlib is shipped via pip, my only concern is that `pygmo` is only available for linux through pip ([refernce](https://esa.github.io/pygmo2/install.html#pip)). I do not know whether I want to drop support for windows and macOS "just" for a bunch of additional functions. 
I also found [`opfunu`](https://github.com/thieunguyen5991/opfunu). With this should be possible to still support all major platforms.

**Comment by NimishVerma** [comment]
I have worked with pygmo in past in Windows as well, I dont have a MAC to check, but pretty sure it works out in MAC too.

**Comment by HaaLeo** [comment]
But you have installed it via `pip`? Ok then I'll give it a try an will check whether it works on macOS, too.

**Comment by HaaLeo** [comment]
Just tried to install `pygmo` via `pip` for macOSX. However it led to the following error:
```bash
(.venv) $ pip3 install pygmo
ERROR: Could not find a version that satisfies the requirement pygmo (from versions: none)
ERROR: No matching distribution found for pygmo
```

I think we cannot use `pygmo` until esa/pygmo2#6 or esa/pygmo2#32 is resolved.

**Comment by alxfmpl** [comment]
What about [`landscapes`](https://github.com/nathanrooy/landscapes)? Looks pretty pythonic to me and has quite a few functions available.

**Comment by HaaLeo** [comment]
Hi @alxfmpl thank you for the suggestion. `landscapes` LGTM.
I just submitted a PR nathanrooy/landscapes#3 to add the [michalewicz function](https://www.sfu.ca/~ssurjano/michal.html) to ensure backwards compability of swarmlib when using it as a dependency.

**Comment by alxfmpl** [comment]
Maybe consider adding it as a optional dependency? I don't think it should be a hard requirement. I'm happy to help with this btw.

**Comment by HaaLeo** [comment]
What are the benefits of using it as an optional dependency? As it is lightweight package in pure python it would be ok for me to add it as normal dependency.

If you want to implement it, I am happy to review a PR on this.
You would basically have to adjust the `main.py` files of each algorithm that uses such a function.
To ensure backwards backwards compability I want the users still to be able to use the michalewicz and ackley functions. 
So you can either wait until nathanrooy/landscapes#3 is merged or do something like:
```
if function == 'michalewicz':
    use swarmlibs implementation of michalewicz
else:
    if function in landscapes and 2D or n-dimensional:
         use landscapes function
    else:
        raise Error function is not supported
```

Maybe the implementation can be encapsulated in the [`functions.py`](https://github.com/HaaLeo/swarmlib/blob/master/swarmlib/util/functions.py), then we do not duplicate that much code. If you face any issues during the implementation, do not hesitate to ping me on [gitter](https://gitter.im/HaaLeo/swarmlib).

**Comment by alxfmpl** [comment]
> To ensure backwards backwards compability I want the users still to be able to use the michalewicz and ackley functions.

I think we're on the same page with this. I'm happy to implement it, but won't get round to have a deeper look into it until the end of the week. Will keep you posted though.

**Comment by nathanrooy** [comment]
Hi @HaaLeo, I've merged your Michalewicz function <a href="https://github.com/nathanrooy/landscapes/pull/3">PR</a> and updated the <a href="https://pypi.org/project/landscapes/">PyPi</a> package.

**Comment by HaaLeo** [comment]
@nathanrooy thanks a lot for merging the PR that quick. I really appreciate it 👍🏼. @alxfmpl will take a look on how we can integrate landscapes into swarmlib later this week.
