### ISSUE TITLE
What if the input of the object function is not 2-dimensional? 

### ISSUE THREAD

**Issue by ji-zhe** [HaaLeo/swarmlib#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaaLeo** [comment]
The the aim of swarmlib is to visualize different swarm-based algorithms for educational purpose. Therefore, it supports only 2D-functions and visualizes their solutions. I do not know how swarmlib behaves if you pass a higher-dimensional function into it. Maybe it returns _some_ solution and visualizes _something_, but I doubt that the returned results are valid. You are welcome to try swarmlib with a higher-dimensional function and post on this issue whether the results are plausible or not.

If your aim is to solely solve general high-dimensional problems with swarm algorithms, I recommend you to use other (more performant) libraries.

I hope I could answer your question.
