### ISSUE TITLE
Cannot import matplotlib

### ISSUE THREAD

**Issue by JhJacky** [HaaLeo/swarmlib#19]
When I started to install the swarmlib I found it worked. But later I used 'swarm --version' to check installing. It happened a error said "ImportError: DLL load failed: 找不到指定的模块。";
 pls help me I preciated much. Thanks.

**Comment by HaaLeo** [comment]
Hi @JhJacky thank you for your contribution. Please add a bit more information. Which python version do you use? Have you tried to install swarmlib in a virtual environment? What are the _exact_ steps to reproduce this error? Maybe you can post the whole stacktrace? (Preferrably in english 😅)

**Comment by JhJacky** [comment]
I used python version 3.7.6 and I successfully create virtual environment (by using "python3 -m venv .venv"). In this point I got another problem which is "source .venv/bin/activate". 
But it told me --'source 'is not an internal or external command or a runnable program or batch file--.

Speaking to the reproducing this error. I just follow the step of readme.md. 
I do nothing special. 

I doubt that I used a new laptop. And there maybe some dependencies which I miss to install. (I tested it on my old computer, and the swarm program works)

PS. I used chinese because I'm a chinese student. And thanks for answer my question. Appreciate a lot.

**Comment by HaaLeo** [comment]
If you are using a windows PC you can activate the virtual environment by running `.venv\Scripts\Activate.ps1` in a powershell instance:
```powershell
PS C:\> .venv\Scripts\Activate.ps1
```
Please retry the installation after you have activated the virtual environment and let me know whether that helps or not. You can read more about virtual environments [here](https://docs.python.org/3/library/venv.html).

**Comment by JhJacky** [comment]
I successfully activate the virtual environment:
![FD3J512`D3YC9T196O I{70](https://user-images.githubusercontent.com/44196198/97720415-38661c80-1b03-11eb-9e93-5424b17e6095.png)
BUT, there still has the same bug like this:
![Z0U$0P$_BP4 7RCQ3%R6@YM](https://user-images.githubusercontent.com/44196198/97720515-52076400-1b03-11eb-804e-2f57db711be9.png)

I searched the solution before, but there seems nobody had problem like me ever.

**Comment by HaaLeo** [comment]
I think this is an issue related to matplotlib. Issue matplotlib/matplotlib#14322 seems very similar to yours. Maybe you want to check your matplotlib backend and its settings. If you cannot resolve the issue on your own I recommend you to ask the folks of the matplotlib repository themselves. 
Since I do not run a windows PC and cannot reprodcue this error, I cannot further support you on this issue unfortunately.

**Comment by JhJacky** [comment]
OK, thanks for your time. I'll figure it out.

**Comment by HaaLeo** [comment]
Feel free to update this issue when you found a way to resolve your problem 🙂 .

**Comment by JhJacky** [comment]
Alright. After my little effort, I finally found where the problem is. If anybody has the same "bug" like me. Pls make sure your PC has installed vs-2015.

**Comment by HaaLeo** [comment]
Thank you for sharing your solution 🙏🏼 .
