### ISSUE TITLE
Read swarmlib's dependencies only from the requirements.txt file

### ISSUE THREAD

**Issue by HaaLeo** [HaaLeo/swarmlib#34]
# Description

Currently swarmlib's dependencies are managed in two files:
* `requirements.txt` for local development
* `setup.py` when bundling and shipping the package

Because of that one must edit both of those files if one changes a dependency. This can be error prone.

# Proposal
Instead of hard coding the dependencies in the `setup.py` as well they can be read from the `requirements.txt` file. The file can be read line by line and then passed to the `setup.py`'s `install_requires` option.

If you consider to pick this issue, please take a look at the [`CONTRIBUTING.md`](https://github.com/HaaLeo/swarmlib/blob/master/CONTRIBUTING.md#how-to-contribute) file first.

**Comment by rhodriguerrier** [comment]
This is my first time contributing so hope this is what you were looking for. Status checks seem to have all passed. PR is at https://github.com/HaaLeo/swarmlib/pull/35

**Comment by HaaLeo** [comment]
Thx for your contribution  🙏🏼 . I just reviewed the changes and merged your PR. 🎉
