### ISSUE TITLE
Is it possible to use Particle Swarm Optimization with custom functions?

### ISSUE THREAD

**Issue by henrique-voni** [HaaLeo/swarmlib#44]
Hello, 

This is not a bug report, but a question about usage. Since i haven't found any documentation on the wiki about this topic, i would like to know if it is possible to use `PSOProblem` with a custom function, instead of using the `FUNCTIONS`  module depicted in [this example](https://github.com/HaaLeo/swarmlib/wiki/Particle-Swarm-Optimization#api). 

Going a little further inside the code i found that all preset functions are wrapped into a specific type. 

Thanks in advance.

**Comment by HaaLeo** [comment]
Hi @henrique-voni I am sure it is. I just have to dig into myself to determine the concrete function signature

**Comment by HaaLeo** [comment]
Hi @henrique-voni I've checked and yes you can use any custom function which has the signature `Callable[[np.ndarray], float]` where np.ndarray is tuple (x, y coordinates). I hope that helps
